name: Pipeline

run-name: Run triggered by ${{github.actor}} ðŸ˜˜

on: [push, workflow_dispatch]

env: 
  DOTNET_INSTALL_DIR: /home/actions-runner/dotnet
  DOTNET_TOOLS_INSTALL_DIR: /home/actions-runner/dotnet-tools
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with: 
          fetch-depth: 0
      - name: Set up .NET 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9
      - name: Build projects
        run: |
          dotnet build Deo.Backend
          dotnet build Deo.Frontend
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: build
          path: |
            **/bin/
            **/obj/
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with: 
          fetch-depth: 0
      - name: Download build artifact
        uses: actions/download-artifact@v5
        with:
          name: build
      - name: Set up .NET 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9
          cache: true
          cache-dependency-path: |
            Deo.Backend.Tests/packages.lock.json
            Deo.Frontend.Tests/packages.lock.json
      - name: Restore dependencies
        run: |
          dotnet restore --locked-mode Deo.Backend.Tests
          dotnet restore --locked-mode Deo.Frontend.Tests
      - name: Test projects
        run: |
          dotnet test --no-restore Deo.Backend.Tests
          dotnet test --no-restore Deo.Frontend.Tests
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: test
          path: |
            **/bin/
            **/obj/
  analyze:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with: 
          fetch-depth: 0
      - name: Download test artifact
        uses: actions/download-artifact@v5
        with:
          name: test
      - name: Set up .NET 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9
          cache: true
          cache-dependency-path: |
            Deo.Backend.Tests/packages.lock.json
            Deo.Frontend.Tests/packages.lock.json
      - name: Set up dotnet tools
        run: |
          dotnet tool install --tool-path "${DOTNET_TOOLS_INSTALL_DIR}" dotnet-sonarscanner
          dotnet tool install --tool-path "${DOTNET_TOOLS_INSTALL_DIR}" dotnet-coverage
      - name: Restore dependencies
        run: |
          dotnet restore --locked-mode Deo.Backend.Tests
          dotnet restore --locked-mode Deo.Frontend.Tests
      - name: Analyze projects
        run: |
          ${DOTNET_TOOLS_INSTALL_DIR}/dotnet-sonarscanner begin \
            /k:"${{ secrets.SONAR_KEY }}" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            /d:sonar.cs.vscoverage.reportsPaths=*.coverage.xml
          ${DOTNET_TOOLS_INSTALL_DIR}/dotnet-coverage collect "dotnet test Deo.Backend.Tests" -f xml -o "backend.coverage.xml"
          ${DOTNET_TOOLS_INSTALL_DIR}/dotnet-coverage collect "dotnet test Deo.Frontend.Tests" -f xml -o "frontend.coverage.xml"
          ${DOTNET_TOOLS_INSTALL_DIR}/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: analyze
          path: "**/*.coverage.xml"            


