name: Packaging Pipeline

run-name: Packaging triggered by ${{ github.actor }}ðŸ‘œ

on: 
  push:
    tags:
      - v*
env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE_NAME: ${{ github.repository }}-backend

jobs:
  build-and-push-backend-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Log in to container REGISTRY
        uses: docker/login-action@v3
        with: 
          registry: $ {{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Extract Metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{env.REGISTRY}}/${{ env.BACKEND_IMAGE_NAME }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./Deo.Backend
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.output.labels}}
      - name: Generate artifact attestations
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{env.REGISTRY}}/${{env.BACKEND_IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest}}
          push-to-registry: true
